# You will need to use type: LoadBalancer so that the frontend can hit the API when loaded in the browser# You might want to use type: LoadBalancer for this one
apiVersion: v1
kind: Service
metadata:
  name: ce-todo-list-project-backend-api-service
spec:
  selector:
    app: ce-todo-list-project-backend-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer